@echo off
REM ###########################################################################
REM PyTorch Intel GPU (OpenCL/SYCL) - One-Click Installer for Windows
REM
REM This script installs everything needed to run PyTorch on Intel Arc/Xe GPUs:
REM   1. Checks for Intel GPU drivers
REM   2. Checks for Intel oneAPI toolkit
REM   3. Installs Python dependencies
REM   4. Builds PyTorch with USE_OPENCL=1
REM
REM Hardware: Intel Arc A-series, Data Center GPU Flex/Max, integrated Xe
REM
REM Usage:
REM   Right-click install_intel_gpu.bat -> Run as Administrator
REM   OR: open cmd as Admin and run install_intel_gpu.bat
REM
REM AI-TRANSLATED: Generated by Claude for Intel GPU backend support.
REM ###########################################################################

setlocal enabledelayedexpansion

echo.
echo ============================================================
echo  PyTorch Intel GPU (OpenCL/SYCL) Installer - Windows
echo ============================================================
echo.

REM ---------------------------------------------------------------------------
REM Pre-flight checks
REM ---------------------------------------------------------------------------
echo [INFO] Running pre-flight checks...

where python >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Python not found. Install Python 3.8+ from python.org first.
    echo         Make sure to check "Add Python to PATH" during install.
    pause
    exit /b 1
)

where pip >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] pip not found. Reinstall Python with pip enabled.
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('python --version 2^>^&1') do set PYVER=%%i
echo [INFO] %PYVER%

REM Get the script directory
set "SCRIPT_DIR=%~dp0"
echo [INFO] Repo: %SCRIPT_DIR%

REM ---------------------------------------------------------------------------
REM Step 1: Check Intel GPU Drivers
REM ---------------------------------------------------------------------------
echo.
echo ==== Step 1/5: Checking Intel GPU drivers ====
echo.

REM Check for Intel GPU via dxdiag-style WMI query
wmic path win32_videocontroller get name 2>nul | findstr /i "Intel Arc" >nul 2>&1
if %errorlevel% equ 0 (
    echo [INFO] Intel Arc GPU detected.
) else (
    wmic path win32_videocontroller get name 2>nul | findstr /i "Intel" >nul 2>&1
    if %errorlevel% equ 0 (
        echo [INFO] Intel GPU detected (may be integrated graphics).
    ) else (
        echo [WARN] No Intel GPU detected. You may need to:
        echo         - Install Intel GPU drivers from:
        echo           https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
        echo         - Make sure your Intel Arc GPU is properly seated
    )
)

echo.
echo [INFO] If you haven't already, install the latest Intel GPU drivers from:
echo        https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
echo.

REM ---------------------------------------------------------------------------
REM Step 2: Check/Install Intel oneAPI
REM ---------------------------------------------------------------------------
echo ==== Step 2/5: Checking Intel oneAPI toolkit ====
echo.

set "ONEAPI_ROOT=C:\Program Files (x86)\Intel\oneAPI"
if exist "%ONEAPI_ROOT%\setvars.bat" (
    echo [INFO] Intel oneAPI found at %ONEAPI_ROOT%
    echo [INFO] Sourcing oneAPI environment...
    call "%ONEAPI_ROOT%\setvars.bat" >nul 2>&1
) else (
    echo [WARN] Intel oneAPI not found at default location.
    echo [WARN] Please install Intel oneAPI Base Toolkit from:
    echo        https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html
    echo.
    echo        Select these components during install:
    echo          - Intel DPC++/C++ Compiler
    echo          - Intel oneAPI Math Kernel Library (oneMKL)
    echo.
    set /p ONEAPI_CUSTOM="Enter custom oneAPI path (or press Enter to continue without it): "
    if defined ONEAPI_CUSTOM (
        if exist "!ONEAPI_CUSTOM!\setvars.bat" (
            call "!ONEAPI_CUSTOM!\setvars.bat" >nul 2>&1
            echo [INFO] Sourced oneAPI from !ONEAPI_CUSTOM!
        ) else (
            echo [WARN] setvars.bat not found at !ONEAPI_CUSTOM!. Continuing without oneAPI.
        )
    )
)

REM ---------------------------------------------------------------------------
REM Step 3: Python dependencies
REM ---------------------------------------------------------------------------
echo.
echo ==== Step 3/5: Installing Python dependencies ====
echo.

cd /d "%SCRIPT_DIR%"

if exist requirements.txt (
    echo [INFO] Installing from requirements.txt...
    pip install -r requirements.txt
)

echo [INFO] Installing build essentials...
pip install pyyaml typing_extensions cmake ninja wheel setuptools

REM ---------------------------------------------------------------------------
REM Step 4: Build PyTorch
REM ---------------------------------------------------------------------------
echo.
echo ==== Step 4/5: Building PyTorch with OpenCL backend ====
echo.

cd /d "%SCRIPT_DIR%"

echo [INFO] Initializing git submodules (pybind11, eigen, etc.)...
echo        This downloads ~2GB of dependencies - may take a few minutes...
git submodule update --init --recursive
if %errorlevel% neq 0 (
    echo [ERROR] Failed to initialize submodules. Check your internet connection.
    pause
    exit /b 1
)
echo [INFO] Submodules initialized.

set USE_OPENCL=1
set USE_CUDA=0
set USE_ROCM=0
set USE_XPU=0
set CMAKE_BUILD_TYPE=Release

echo [INFO] Build configuration:
echo         USE_OPENCL=1, USE_CUDA=0
echo         This will take 30-60+ minutes...
echo.

pip install -e . -v --no-build-isolation > build_opencl.log 2>&1
type build_opencl.log | findstr /i "error fatal failed successfully"

if %errorlevel% neq 0 (
    echo [ERROR] Build failed. Check build_opencl.log for details.
    pause
    exit /b 1
)

REM ---------------------------------------------------------------------------
REM Step 5: Verify
REM ---------------------------------------------------------------------------
echo.
echo ==== Step 5/5: Verifying installation ====
echo.

python -c "import torch; print(f'PyTorch {torch.__version__}'); import torch.opencl; print(f'OpenCL available: {torch.opencl.is_available()}')"

REM ---------------------------------------------------------------------------
REM Done
REM ---------------------------------------------------------------------------
echo.
echo ============================================================
echo  Installation complete!
echo ============================================================
echo.
echo  To use in future sessions:
echo    1. Open cmd
echo    2. Run: "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
echo    3. Then: python -c "import torch; x = torch.randn(3,3, device='opencl')"
echo.
echo  See INTEL_GPU_README.md for full documentation.
echo.
echo  Build log: %SCRIPT_DIR%build_opencl.log
echo.

pause
