#!/bin/bash
###############################################################################
# PyTorch Intel GPU (OpenCL/SYCL) - One-Click Installer
#
# This script installs everything needed to run PyTorch on Intel Arc/Xe GPUs:
#   1. Intel GPU drivers
#   2. Intel oneAPI Base Toolkit (DPC++ compiler + oneMKL)
#   3. Python dependencies
#   4. Builds PyTorch with USE_OPENCL=1
#
# Supported: Ubuntu 22.04, 24.04 (x86_64)
# Hardware:  Intel Arc A-series, Data Center GPU Flex/Max, integrated Xe
#
# Usage:
#   chmod +x install_intel_gpu.sh
#   ./install_intel_gpu.sh
#
# AI-TRANSLATED: Generated by Claude for Intel GPU backend support.
###############################################################################

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()   { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
step()  { echo -e "\n${BLUE}==== $1 ====${NC}\n"; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
step "Pre-flight checks"

if [[ "$EUID" -eq 0 ]]; then
    error "Do not run this script as root. It will ask for sudo when needed."
fi

if [[ ! -f /etc/os-release ]]; then
    error "Cannot detect OS. This installer supports Ubuntu 22.04/24.04."
fi

source /etc/os-release
if [[ "$ID" != "ubuntu" ]]; then
    warn "Detected $ID $VERSION_ID. This installer is tested on Ubuntu 22.04/24.04."
    warn "Proceeding anyway — some steps may need manual adjustment."
fi

if ! command -v python3 &>/dev/null; then
    error "python3 not found. Install Python 3.8+ first."
fi

if ! command -v pip &>/dev/null && ! command -v pip3 &>/dev/null; then
    warn "pip not found. Attempting to install..."
    sudo apt-get update && sudo apt-get install -y python3-pip
fi

PYTHON=$(command -v python3)
PIP=$(command -v pip3 || command -v pip)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log "OS: $ID $VERSION_ID"
log "Python: $($PYTHON --version)"
log "Repo: $SCRIPT_DIR"

# ---------------------------------------------------------------------------
# Step 1: Intel GPU Drivers
# ---------------------------------------------------------------------------
step "Step 1/5: Installing Intel GPU drivers"

if command -v clinfo &>/dev/null && clinfo 2>/dev/null | grep -qi "intel"; then
    log "Intel GPU drivers already detected. Skipping driver install."
else
    log "Adding Intel GPU repository..."
    sudo apt-get install -y gpg-agent wget

    wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | \
        sudo gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg

    CODENAME=$(lsb_release -cs 2>/dev/null || echo "jammy")
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu $CODENAME unified" | \
        sudo tee /etc/apt/sources.list.d/intel-gpu-$CODENAME.list

    sudo apt-get update

    log "Installing GPU runtime packages..."
    sudo apt-get install -y \
        intel-opencl-icd \
        intel-level-zero-gpu \
        level-zero \
        intel-media-va-driver-non-free \
        libmfx1 \
        libmfxgen1 \
        libvpl2 \
        clinfo \
        || warn "Some driver packages may not be available for your Ubuntu version."

    log "Verifying GPU detection..."
    if clinfo 2>/dev/null | grep -qi "intel"; then
        log "Intel GPU detected successfully."
    else
        warn "No Intel GPU detected by clinfo. You may need to:"
        warn "  - Reboot after driver install"
        warn "  - Add your user to the 'render' group: sudo usermod -aG render $USER"
        warn "  - Check that your GPU is supported"
    fi
fi

# Add user to render group if not already
if ! groups | grep -q render; then
    log "Adding $USER to 'render' group for GPU access..."
    sudo usermod -aG render "$USER"
    warn "You may need to log out and back in for group changes to take effect."
fi

# ---------------------------------------------------------------------------
# Step 2: Intel oneAPI Toolkit
# ---------------------------------------------------------------------------
step "Step 2/5: Installing Intel oneAPI toolkit"

if [[ -f /opt/intel/oneapi/setvars.sh ]]; then
    log "Intel oneAPI already installed. Skipping."
else
    log "Adding Intel oneAPI repository..."
    wget -qO- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | \
        gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null

    echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | \
        sudo tee /etc/apt/sources.list.d/oneAPI.list

    sudo apt-get update

    log "Installing DPC++ compiler and oneMKL (this may take a while)..."
    sudo apt-get install -y \
        intel-oneapi-compiler-dpcpp-cpp \
        intel-oneapi-mkl-devel \
        || error "Failed to install oneAPI packages."
fi

log "Sourcing oneAPI environment..."
source /opt/intel/oneapi/setvars.sh 2>/dev/null || warn "Could not source setvars.sh"

# ---------------------------------------------------------------------------
# Step 3: Python dependencies
# ---------------------------------------------------------------------------
step "Step 3/5: Installing Python dependencies"

cd "$SCRIPT_DIR"

if [[ -f requirements.txt ]]; then
    log "Installing from requirements.txt..."
    $PIP install -r requirements.txt
fi

log "Installing build essentials..."
$PIP install pyyaml typing_extensions cmake ninja wheel setuptools

# ---------------------------------------------------------------------------
# Step 4: Build PyTorch with OpenCL
# ---------------------------------------------------------------------------
step "Step 4/5: Building PyTorch with OpenCL backend"

cd "$SCRIPT_DIR"

# Make sure we're on the right branch
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
if [[ "$CURRENT_BRANCH" != "claude/cuda-to-opencl-translation-kl8Ms" && "$CURRENT_BRANCH" != "main" ]]; then
    warn "On branch '$CURRENT_BRANCH'. Expected 'main' or feature branch."
fi

export USE_OPENCL=1
export USE_CUDA=0
export USE_ROCM=0
export USE_XPU=0
export CMAKE_BUILD_TYPE=Release
export MAX_JOBS=$(( $(nproc) > 8 ? 8 : $(nproc) ))

log "Build configuration:"
log "  USE_OPENCL=1, USE_CUDA=0"
log "  MAX_JOBS=$MAX_JOBS"
log "  This will take 30-60+ minutes..."

$PIP install -e . -v --no-build-isolation 2>&1 | tee build_opencl.log

if [[ $? -ne 0 ]]; then
    error "Build failed. Check build_opencl.log for details."
fi

# ---------------------------------------------------------------------------
# Step 5: Verify installation
# ---------------------------------------------------------------------------
step "Step 5/5: Verifying installation"

$PYTHON -c "
import torch
print(f'PyTorch version: {torch.__version__}')

try:
    import torch.opencl
    available = torch.opencl.is_available()
    print(f'OpenCL available: {available}')
    if available:
        print(f'Device count: {torch.opencl.device_count()}')
        x = torch.randn(3, 3, device=\"opencl\")
        y = torch.randn(3, 3, device=\"opencl\")
        z = x + y
        print(f'Tensor on Intel GPU: {z.device}')
        print(f'Result: {z}')
        print()
        print('Intel GPU backend is working!')
    else:
        print('OpenCL module loaded but no device available.')
        print('Make sure Intel GPU drivers are installed and GPU is detected.')
except Exception as e:
    print(f'OpenCL verification error: {e}')
    print('The build completed but runtime verification failed.')
    print('This may be expected if no Intel GPU is present on this machine.')
"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
step "Installation complete"

log "To use in future sessions, source oneAPI first:"
log "  source /opt/intel/oneapi/setvars.sh"
log ""
log "Then use PyTorch normally with device='opencl':"
log "  import torch"
log "  x = torch.randn(3, 3, device='opencl')"
log ""
log "See INTEL_GPU_README.md for full documentation."
log ""
log "Build log saved to: $SCRIPT_DIR/build_opencl.log"
